### PR TITLE
Add support for graphs containing cycles

### PR DESCRIPTION
**Pull request by mjambon**
Hello Daniil!

I really appreciate the simplicity of this library. Thank you for putting it out there! I decided to add support for dealing with cyclic graphs. My use case is generating OCaml code such as type definitions or functions derived from such type definitions. Consider the following OCaml program:

```ocaml
type a = b
and b = { x: c }
and c = b option
```
Instead, we'd like to emit the following code:
```ocaml
type b = { x: c }
and c = b option

type a = b
```

To achieve this, we perform a topological sort on the DAG obtained by collapsing the cyclic regions of the graph. I left the details in the code.

I realize this is a large pull request. I tried to make it as easy to review as possible. A couple remarks:

* I've maintained compatibility with the old API, so far. This means the library offers a single top-level module called `Tsort`. Dune doesn't let us have another module next to it because this module has the same name as the library that contains it. If the library's name was something else, say `Foo`, then we could have `Foo.Tsort` and `Foo.Components` each derived from separate ml files. Anyway, it's just something to remember if we're willing to break compatibility in the future.
* I added tests. This uses the `alcotest` library. It's only required for `make test`. Use `opam install alcotest` to install it.
* In the new code, missing nodes are added silently instead of producing an error. If you like it, we could do the same for `Tsort.tsort`, which simplifies the result type but is slightly different.

I would also like to add some CI testing, which will allow us to test compatibility with older OCaml versions (e.g. for recent functions like `Hashtbl.find_opt`). It would be more convenient than finding this out when submitting opam package to opam-repository. I've used CircleCI lately and I'd be happy to set it up.

Please let me know what you think overall, when you get a chance!

Thanks,
Martin

### CODE REVIEW

**Comment by dmbaturin** [comment]
This is a valuable addition. Thanks for your work!

First a small thing: would it be possible to move files to `src/lib` using `git mv` to preserve their history?

Also, maybe expose `Tsort.sort_strongly_connected_components` and `Tsort.find_strongly_connected_components` rather than use a nested module? Just an idea.

Now to the hard parts:
>missing nodes are added silently instead of producing an error

Could you name a use case when dependencies on non-existent nodes are normal and silently inserting them creates a valid state?

I think `Components.sort` should have at least an option to fail if there are missing nodes. For example, an init system may treat circular dependencies between daemons as "must always be running together", but dependencies on non-existent services should be detectable.

I'm using the lib for scheduling processing steps (e.g. HTML manipulation rules in [soupault](https://soupault.neocities.org/reference-manual/#widget-processing-order)), so my assumption was that bad dependencies are very likely to appear due to user errors, and should be considered an illegal state.
Consider a makefile written by a distracted user:

```
build:
    ...
test:
    ...
install: bluid tset
```

With the current design, the typos will be detected after parsing and sorting, there is no need for additional validation. While checking for non-existent dependencies is no worse than O(|E|), it's still a separate step, but now the user gets it for free.

Of course, if you already have validation in place, or if non-existent dependencies is not an illegal state, that's just a nuisance.

Maybe it's a good idea to add an optional argument like `?(insert_missing_nodes=false)` to both `Tsort.sort` and `Tsort.Components.sort` so that one can choose how to treat them.

**Comment by mjambon** [comment]
Thanks for your quick reply!

> First a small thing: would it be possible to move files to src/lib using git mv to preserve their history?

I'll do something about it. I used `git mv` but the problem is that it doesn't track the relocations. It's the same as creating a new file and deleting the file at the old location. It turns out we can get a reasonable diff using the `-M` option, from the command line:
```
git diff -M30% master
```
but I'm not sure how to achieve this on github. Maybe I'll just break the pull request into two.

> Also, maybe expose Tsort.sort_strongly_connected_components and Tsort.find_strongly_connected_components rather than use a nested module? Just an idea.

Sounds reasonable from a user perspective. (I like to use submodules in my source code to group things in logical units but this structure may not be useful to the user)

> Could you name a use case when dependencies on non-existent nodes are normal and silently inserting them creates a valid state?

It is useful when writing the graph by hand, typically for testing purposes. For example, we'd only write `[1, [2]]` instead of `[1, [2]; 2, []]`. Note that dot (from graphviz) operates like this. Another advantage is that it simplifies the signature of the ocaml functions.

> I think Components.sort should have at least an option to fail if there are missing nodes. For example, an init system may treat circular dependencies between daemons as "must always be running together", but dependencies on non-existent services should be detectable.

This makes sense. I note that such detection can be done independently and doesn't require a tricky algorithm. I tend to err on the side of decoupling the different concerns, which in this case means providing a separate function for doing this detection. I need to play with this a bit. I'll propose something.

To recapitulate, you should expect the following from me:

1. a simpler pull request that only takes care of the code reorganization, without changes in `tsort.ml`, followed by another pull request with the rest of the code.
2. proposals for the new `Tsort` module interface.

**Comment by dmbaturin** [comment]
>I used git mv but the problem is that it doesn't track the relocations.

Maybe my memory doesn't serve me well. I'm almost certain that I did history-preserving renames somehow, but I can't remember what my procedure was.
Well, if there's no easy way, that's not a big deal.

>I like to use submodules in my source code to group things in logical units but this structure may not be useful to the user

Myself I wouldn't immediately associate "Components" with strongly connected components. `Tsort.sort_strongly_connected_components` is long, but at least it's understandable even without docs.

>It is useful when writing the graph by hand, typically for testing purposes.
> Note that dot (from graphviz) operates like this.
>Another advantage is that it simplifies the signature of the ocaml functions.

The main philosophical problem with my optional argument idea is that the behavior distinction is indeed impossible to reflect in the types.

Since `find_nonexistent_nodes` is a separate function, the simplest solution may be to just expose it and make the sort functions insert missing nodes silently indeed.

Since the only project that (publicly) depends on this package is my own, I think breaking the API isn't a big deal—in fact, if we are to do it, better do it now before anyone else starts using it.

**Comment by mjambon** [comment]
This gives us the following signature for the `Tsort` module:
```ocaml
type 'a sort_result =
  | Sorted of 'a list
  | ErrorCycle of 'a list

val sort : ('a * 'a list) list -> 'a sort_result
val sort_strongly_connected_components : ('a * 'a list) list -> 'a list list
val find_strongly_connected_components : ('a * 'a list) list -> 'a list list
val find_nonexistent_nodes : ('a * 'a list) list -> 'a list
```

Notes:
* This breaks compatibility with earlier versions. I would increment the package's version to 2.0.0 to reflect this [according to semver rules](https://semver.org/) and call it a day.
* Both sort functions now add nonexistent nodes rather than complaining about it.

I'm updating the code accordingly.

**Comment by dmbaturin** [comment]
For your use case, will it harm if I change the `find_nonexistent_nodes` function to `→ (α × α list) list` so that it reports which nodes have bad dependencies and what those dependencies are?

**Comment by mjambon** [comment]
Feel free to change `find_nonexistent_nodes`, it's not in use by the library itself.

**Pull request merged**
