### PR TITLE
Esy support

### PR DESCRIPTION
**Pull request by superherointj**
Would you accept adding Esy support?
Thanks.

### CODE REVIEW

**Comment by dmbaturin** [comment]
I'm by no means against Esy, but my knowledge of it is limited to "I heard it exists" yet.
I'm happy to merge it if it helps esy users, but I need to know how do I make sure the packaging is still working right if I change something. What is the standard way to sanity check esy packaging?

**Comment by superherointj** [comment]
Esy creates an isolated environment / sandbox per project to build the project, it downloads packages from OPAM/NPM/GIT repositories, and abstracts away the need of using opam (for downloading packages). It's use is optional. And the proposed changes do not effect how your package works or how it should be published in OPAM. It is mostly a convenience for Esy users that don't have system wide installation of Opam, Merlin or even OCaml. If you need to add new dependencies, you can just add them in dependencies field as `"@opam/new_package_name": "*"` in `package.json`. But at any trouble I can keep it updated myself. It is quite simple.

**Comment by superherointj** [comment]
Regarding 'sanity check'. I think I could include some test for it or automate the process in CI. By just doing 'esy' (which installs packages) and seeing if it fails. I'll give some thought to this. Likely only manipulating dependencies would break it.

**Comment by superherointj** [comment]
I could provide a Dockerfile for testing building the project when using Esy if you wish. The content would be something like:

> FROM superherointj/archlinux-esy AS batci-builder
> COPY src ./src/
> COPY *.opam *.json dune dune-project Makefile ./
> RUN npm run install
> RUN npm run build
> RUN npm run test
> RUN npm run clean

If that is acceptable I could save it in `./Dockerfile.esy`. It would work if built as:
`docker build -f Dockerfile.esy -t tsort-esy .`

**Comment by dmbaturin** [comment]
Maybe add the dockerfile to the repo for a reference, or include it in the README?

**Comment by dmbaturin** [comment]
Thanks for the dockerfile. I sure need to look into esy and see if I can benefit from it myself.

**Pull request merged**
